apiVersion: v1
kind: Service
metadata:
  name: {{ include "v55app-chart.fullname" . }}
  labels:
    {{- include "v55app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
       targetPort: {{ .Values.service.targetPort }}
       protocol: {{ .Values.service.protocol }}
       name: {{ .Values.service.name }}
  selector:
    {{- include "v55app-chart.selectorLabels" . | nindent 4 }}
