pipeline {
    agent any

    parameters {
        string(name: 'EKS_CLUSTER_NAME', defaultValue: '', description: 'Enter the name of the EKS cluster')
        choice(name: 'REGION', choices: ['us-west-1', 'us-west-2'], description: 'Select the AWS REGION where you want to create EKS CLuster')
        choice(name: 'ACTION', choices: ['Create', 'Destroy'], description: 'Select whether to apply or destroy resources')       
    }
    
    
    stages {   
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Git Checkout') {
            steps {
                script {
                    withVault(configuration: [disableChildPoliciesOverride: false, timeout: 60, vaultCredentialId: 'vault-token', vaultUrl: 'http://54.219.228.70:8200'], vaultSecrets: [
                          [path: 'secrets/github', secretValues: [[envVar: 'GITHUB_USER', vaultKey: 'user'], [envVar: 'GITHUB_TOKEN', vaultKey: 'github_token']]]
                    ]) {
                        echo "Cloning the GitHub Repository"
                        sh """
                        git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/RajDevO/jenkins-tf-eks.git
                        """
                    }
                }
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    dir("${WORKSPACE}/jenkins-tf-eks/eks-Iac") {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    dir("${WORKSPACE}/jenkins-tf-eks/eks-Iac") {
                        sh "terraform plan -out=tfplan -var cluster_name=${params.EKS_CLUSTER_NAME}"
                        sh 'terraform show -no-color tfplan > tfplan.txt'
                    }
                }
            }
        }

       stage('Apply or Destroy Resources') {
            steps {
                script {
                    if (params.ACTION == 'Create') {
                        echo "Creating EKS Cluster..."
                        sh "terraform apply -auto-approve -var cluster_name=${params.EKS_CLUSTER_NAME} -var region=${params.REGION}"
                    } else if (params.ACTION == 'Destroy') {
                        echo "Destroying EKS Cluster.."
                        sh "terraform destroy -auto-approve -var cluster_name=${params.EKS_CLUSTER_NAME} -var region=${params.REGION}"
                    }
                }
            }
        }
        stage('State list') {
            steps {
                script {
                    dir("${WORKSPACE}/jenkins-tf-eks/eks-Iac") {
                        sh 'terraform state list'
                    }
                }
            }
        }
    }
}
