apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-inject-secret-db-password: 'secret/my-app/db-password'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-app
          image: 'docker.io/hello-world-app:latest'
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: db-password
          ports:
            - containerPort: 8080
